# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='count',
        ),
    ]
