# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0006_auto_20170613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('N', 'N\xe1poje'), ('J', 'J\xeddlo'), ('O', 'Ostatn\xed')], default='N', max_length=1, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='beercounter.Bill'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beercounter.Item'),
        ),
    ]
