# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0009_auto_20170615_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='beercounter.Item'),
        ),
    ]
