# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0011_auto_20170615_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
