# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beercounter', '0015_auto_20170711_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
