# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beercounter', '0016_pub_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pub',
            unique_together=set([('name', 'owner')]),
        ),
    ]
