# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0018_auto_20170712_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='isBase',
            field=models.BooleanField(default=False),
        ),
    ]
