# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beercounter', '0019_pub_isbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='isBase',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=51, unique=True, verbose_name='N\xe1zev'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=51, unique=True, verbose_name='N\xe1zev'),
        ),
    ]
