# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beercounter', '0020_auto_20170712_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isBase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='isBase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pub',
            name='isBase',
            field=models.BooleanField(default=False),
        ),
    ]
